#! /usr/bin/env ruby 

require 'optparse'

MAX = 10000

module GachaCore
  class << self
    def gacha(drop_rate)
      threashold = MAX * (drop_rate / 100)
      hit = Random.rand(1 .. MAX)
      result = false

      if hit <= threashold then
        result = true
      end
      result
    end

    def gacha_streak(drop_rate, step, price)

      result = []
      step.times do
        result.push(gacha(drop_rate))
      end
      result
    end
  end
end

module ResultWriter
  class << self
    def write_result(results, drop_rate, step, price)
      total_price = step * price
      actual_jackpot_rate = calc_jackpot_rate(results)
      expected_jackpot_rate = drop_rate * step
      prefix = <<-EOS

お目当てのドロップ率 #{drop_rate}%
実際に出たお目当てドロップ率 #{actual_jackpot_rate}%
予想されるお目当てドロップ率（お目当てドロップ率 * 回数） #{expected_jackpot_rate}%   
連続数 #{step}連
使用金額 #{total_price}円 

----------------------------------------------------------------------------------

      EOS
      STDOUT.puts  prefix

      results.each_with_index do |result, idx| 
        result_text = "はずれ…"
        idx_text = "#{idx+1}".rjust(8)
        if result then
          result_text = "あたり！"
        end
        realtime_burned_price = write_realtime_burned_price(idx, price)
        realtime_expected_jackpot_rate = "#{calc_realtime_expected_jackpot_rate(idx, drop_rate)}".rjust(7)
        output_text = " #{idx_text}\s連 -> #{result_text.rjust(5)}\t#{realtime_burned_price}\t期待される出現率 #{realtime_expected_jackpot_rate} %"
        STDOUT.puts output_text
      end

    end

    def calc_jackpot_rate(results)
      jackpots = results.select { |result| result == true}

      jackpots.size.to_f / results.size.to_f * 100
    end

    def write_realtime_burned_price(idx, price)
      calced = "#{(idx+1) * price}".rjust(7)
      "(#{calced} 円)"
    end
    def calc_realtime_expected_jackpot_rate(idx, drop_rate)
      (idx+1) * drop_rate
    end

    def color_decide(result)
    end
  end
end

drop_rate = 3.0
step = 10
price = 300

opt = OptionParser.new
opt.on('-d', '--drop DROP_RATE', 'set drop_rate') { |v| drop_rate = v.to_f }
opt.on('-s', '--step STEP', 'set steps') { |v| step = v.to_i }
opt.on('-p', '--price PRICE', 'set price') { |v| price = v.to_i }
opt.parse(ARGV)

result = GachaCore.gacha_streak(drop_rate, step, price)

ResultWriter.write_result(result, drop_rate, step, price)
